### ISSUE TITLE
Composer dependency for phpseclib upgrade

### ISSUE THREAD

**Issue by RV7PR** [thephpleague/flysystem-sftp#110]
phpseclib 3.0.0 is out, when will this be updated?
I use phpseclib myself for ssh connections, but I can't upgrade because flysystem depends on V2

**Comment by AdamGaskins** [comment]
This would be great. Phpseclib 2.x is a bit behind as far as supported ciphers etc.

**Comment by maxhelias** [comment]
You can use https://github.com/thephpleague/flysystem-sftp-v3
