### ISSUE TITLE
Installing "league / flysystem-sftp"  Laravel and  PHP 8

### ISSUE THREAD

**Issue by hi2binay** [thephpleague/flysystem-sftp#112]
Hi There,

I am getting errors when trying to install this package on Laravel and PHP 8, attached are the screen shot.
please have a look and help me to install it.

![error](https://user-images.githubusercontent.com/3139539/103408395-56dea780-4b88-11eb-8225-2560df8ecdc9.PNG)
![error-with-version](https://user-images.githubusercontent.com/3139539/103408399-58a86b00-4b88-11eb-9257-6fbccf662a92.PNG)
![composer-json](https://user-images.githubusercontent.com/3139539/103408400-59d99800-4b88-11eb-8a76-28d59d1c9bdf.PNG)
![php](https://user-images.githubusercontent.com/3139539/103408402-5b0ac500-4b88-11eb-8c68-b87ff4675190.PNG)

Thanks & Regards
Binay Kumar

**Comment by mybigman** [comment]
same issue

**Comment by sunxyw** [comment]
same issue

**Comment by gpibarra** [comment]
same issue

**Comment by gpibarra** [comment]
Work to me: `composer require league/flysystem-sftp:^1`

**Comment by frankdejonge** [comment]
The docs state how to install it, which includes this version constraint. So the mention from @gpibarra is correct.
