### ISSUE TITLE
Unwated duplication of folder on call to move

### ISSUE THREAD

**Issue by AntonioCS** [thephpleague/flysystem-sftp#118]
Hello,
I'm using the sftp adapter to copy some files from an sftp server, and after the copy I want to move the files I copied to another folder.
So the ftp has the current folder structure:
![image](https://user-images.githubusercontent.com/1086401/107113425-c23a2a00-6856-11eb-821a-999cce6f42c5.png)
So when I read some files from the `client1-uploads` folder I move it to the archive folder... but for some strange reason I'm getting the client and archive folder duplicated inside the `client1-uploads` folder, so after I move the files I will have this:
![image](https://user-images.githubusercontent.com/1086401/107113507-45f41680-6857-11eb-97c8-ea98f9d6544e.png)

Note that the files `file1` and `file2` are now inside the `archive` folder but I now have another `client1-uploads` with an `archive` folder inside the `client1-uploads` folder.
Note: This sftp server is something from amazon, and when I log in (using filezilla) I'm redirected to the `client1-uploads` folder, I am not able to access `root` (/).

Here is the connection code: 
```
        $filesystem = new Filesystem(new SftpAdapter(
            new SftpConnectionProvider(
                $config['host'],
                $config['username'],
                $config['password'] ?? null,
                $config['private_key'],
                null,
                $config['port'] ?? 22,
                false,
                30,
                10,
                null,
                null
            ),
            $rootFolder, // root path (required)
            PortableVisibilityConverter::fromArray([
                'file' => [
                    'public' => 0640,
                    'private' => 0604,
                ],
                'dir' => [
                    'public' => 0740,
                    'private' => 7604,
                ],
            ])
        ));
```
`$rootFolder` = `/client1-uploads`

I then do a listing:
```
 $validFiles = $filesystem->listContents($listFolderFtp ?? $rootFolder);
 ```
Here `$listFolderFtp` is just `/` as I was getting errors if I used the `$rootFolder` for listing.

After getting the files (I also do some filtering where I just get the paths), I loop them and do my copy to local disk:
```
        $fileCount = 0;
        /** @var string $file */
        foreach ($validFiles as $file) {
            $fileCount++;
            $fname = basename($file);
            file_put_contents("$folderDestination/$fname", $filesystem->read($file));

            if ($archiveReadTo) {
                $filesystem->move($file, "$archiveReadTo/$fname");
            }
        }
  ```
  **This all works**. I get the files on local disk and I do get the files that I've read moved to the `archive` folder, BUT I also get the duplication of the folder structure.

**Comment by DeCodeerHeer** [comment]
Experiencing the same issue. It seems to somehow include the root folder declared in the SftpConnectionProvider twice.
`/data` is my root folder
```
/data/test1.txt
```
becomes
```
/data/data/test1.txt
```
when utilizing the move method.

Reverted to copy & delete for now, would be nice to get this fixed.
