### ISSUE TITLE
Via proxy

### ISSUE THREAD

**Issue by auro1** [thephpleague/flysystem-sftp#13]
Hey

I've been unable to figure out how to connect via a proxy?! I've searched on google, stackoverflow and your issues. Perhaps I'm blind? :+1:

**Comment by auro1** [comment]
I can add that I have access to either a SOCKS5 or a http proxy

**Comment by auro1** [comment]
Perhaps there is a way to throw a Net_SSH2 object into the constructor?

**Comment by frankdejonge** [comment]
@auro1 You can now inject the connection under the `"NetSftpConnection"` config key in the constructor. Fixed in 1.0.7
