### ISSUE TITLE
API flysystem->copy returns null on success

### ISSUE THREAD

**Issue by olivier-novalend** [thephpleague/flysystem-sftp#131]
Hi,

if I `dump($this->filesystem->copy($object['path'], str_replace($this->directoryGet, $this->directoryArchive, $object['path'])));`, the output of the dump is null, not true (as indicated in the doc https://flysystem.thephpleague.com/v1/docs/usage/filesystem-api/).

The copy works well though.

But it is a problem because I can’t use the response of my copy in a if, ie
`if($this->filesystem->copy($object['path'], str_replace($this->directoryGet, $this->directoryArchive, $object['path']))) {}`

**Comment by frankdejonge** [comment]
@olivier-novalend what version do you have installed?

**Comment by olivier-novalend** [comment]
"league/flysystem-bundle": "^2.0",
		"league/flysystem-sftp": "^2.2",

**Comment by frankdejonge** [comment]
then what you're seeing is correct, you're linking the old docs, the new ones are here: https://flysystem.thephpleague.com/v2/docs/usage/filesystem-api/#filesystemwritercopy

**Comment by olivier-novalend** [comment]
Oh I see…
Thanks
