### ISSUE TITLE
Is StubSftpConnectionProvider supposed to be internal?

### ISSUE THREAD

**Issue by jschaedl** [thephpleague/flysystem-sftp#133]
I encountered an issue with the `StubSftpConnectionProvider` class while trying to use it in one of my test:

```
Error: Class "League\Flysystem\PhpseclibV2\SftpStub" not found

.../vendor/league/flysystem-sftp/StubSftpConnectionProvider.php:51
```

It is instantiating a `SftpStub` object here: 
https://github.com/thephpleague/flysystem-sftp/blob/3.x/StubSftpConnectionProvider.php#L54
but the class `SftpStub` is not part of the released package. 

After investigating a bit, I figured that this is probably due to the fact of this class being marked as `@internal`: https://github.com/thephpleague/flysystem-sftp/blob/3.x/SftpStub.php#L10

Would you consider to include the `SftpStub` class in the released packages, so the `StubSftpConnectionProvider` could be used? I am happy to send a fix.

**Comment by frankdejonge** [comment]
Hi @jschaedl, the stub connection provider is only used for testing this package. You shouldn't be using it.

**Comment by jschaedl** [comment]
Hi @frankdejonge fair enough. Will try to find an alternative for my test. Thanks a lot for the quick answer. Closing the issue then.
