### ISSUE TITLE
PHP7 compatibility - Net_SFTP has a deprecated constructor

### ISSUE THREAD

**Issue by soee** [thephpleague/flysystem-sftp#14]
Hi,

we are trying our Laravel app to run on machine with PHP7. Now when some file transfer should be done it ends with this error:

`Methods with the same name as their class will not be constructors in a future version of PHP; Net_SFTP has a deprecated constructor`

Is it related to this package or phpseclib/phpseclib and the version of it flysystem-sftp depends ?

Looks like phpseclib 2.0 branch should have fixed it [see this](https://github.com/phpseclib/phpseclib/issues/734)

**Comment by judgej** [comment]
Wow, I thought those kinds of constructors had been removed years ago.

It seems that just having a `__construct()` method is enough to stop this warning, without breaking older version compatibility (which presumably phpseclib 0.3.8 is trying to retain).

``` php
class Filter {
    function __construct() {
        $this->filter($a);
    }

    // Old constructor.
    function filter($a) {}
}
```

Anyway, that's for them to sort out if still supporting that old version. Just thinking out aloud.
