### ISSUE TITLE
Passphrase for private key

### ISSUE THREAD

**Issue by tyloo** [thephpleague/flysystem-sftp#30]
Hello,

I need to implement your package to connect a sftp using a privateKey and an associated passphrase. I cannot provide this passphrase using your package.

Do you have an idea please ? Thanks a lot in advance

**Comment by frankdejonge** [comment]
@tyloo you can use the password for that, it's used as the passphrase.

**Comment by frankdejonge** [comment]
For future spectators of this issue (COUGH pietro COUGH), this should be the `passphrase` option.
