### ISSUE TITLE
Example in Readme seems to be outdated

### ISSUE THREAD

**Issue by andreasschroth** [thephpleague/flysystem-sftp#32]
Setting "'agent' => true" inside the Config array (as stated in the Readme) leads to the following error message:

`TypeError: Argument 1 passed to League\Flysystem\Sftp\SftpAdapter::setAgent() must be an instance of phpseclib\System\SSH\Agent, boolean given, called in /src/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php on line 112`

**Comment by frankdejonge** [comment]
Thanks for the PR.
