### ISSUE TITLE
vendor/league/flysystem-sftp does not exist and could not be created.

### ISSUE THREAD

**Issue by bunlongheng** [thephpleague/flysystem-sftp#40]
**composer require league/flysystem-sftp**

I got 

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^1.0 for league/flysystem-sftp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

                                                                                                                        
  [RuntimeException]                                                                                                    
  /Applications/MAMP/htdocs/code/web-app/vendor/league/flysystem-sftp does not exist and could not be created.
```

How do I avoid that ?

**Comment by frankdejonge** [comment]
@bunlongheng this seems to be a local composer/vendor-dir permission problem, not a problem with Flysystem issue.

**Comment by frankdejonge** [comment]
I'd advice to look at the permissions of the vendor dir and project level permissions.

**Comment by bunlongheng** [comment]
My folder directory look like this

-rw-r--r--   1 bheng  staff     777 Feb 27 20:18 phpunit.xml
-rw-r--r--   1 bheng  staff      87 Feb 27 20:18 phpspec.yml
-rw-r--r--   1 bheng  staff     481 Feb 27 20:18 package.json
drwxr-xr-x   3 bheng  staff     102 Feb 27 20:18 note
-rw-r--r--   1 bheng  staff     967 Feb 27 20:18 md-bheng-readme.txt
-rw-r--r--   1 bheng  staff     503 Feb 27 20:18 gulpfile.js
-rw-r--r--   1 bheng  staff      26 Feb 27 20:18 contributors.txt
-rw-r--r--   1 bheng  staff    1635 Feb 27 20:18 artisan
-rw-r--r--   1 bheng  staff      43 Feb 27 20:18 Procfile
-rw-r--r--   1 bheng  staff    5634 Feb 27 20:18 Gruntfile.js
drwxr-xr-x   4 bheng  staff     136 Feb 27 20:18 tests
drwxr-xr-x   5 bheng  staff     170 Feb 27 20:18 storage
drwxr-xr-x   4 bheng  staff     136 Feb 27 20:18 sql
-rw-r--r--   1 bheng  staff     560 Feb 27 20:18 server.php
drwxr-xr-x   5 bheng  staff     170 Feb 27 20:18 resources
-rw-r--r--   1 bheng  staff     105 Feb 27 20:18 pull.sh
drwxr-xr-x   7 bheng  staff     238 Mar  1 14:46 bootstrap
-rw-r--r--@  1 bheng  staff       0 Mar  1 14:46 Icon?
drwxr-xr-x  22 bheng  staff     748 Mar  2 11:47 app
drwxrwxrwx@ 27 bheng  staff     918 Mar  3 14:55 public
drwxr-xr-x   8 bheng  staff     272 Mar  6 13:25 database
-rw-------@  1 bheng  staff     405 Mar 14 09:29 id_rsa.pub
-rw-------   1 bheng  staff    1766 Mar 14 09:29 id_rsa
drwxr-xr-x  18 bheng  staff     612 Mar 14 09:30 config
-rw-r--r--   1 bheng  staff     988 Mar 14 09:57 composer.json
-rw-r--r--   1 bheng  staff  126713 Mar 14 10:00 composer.lock
drwxr-xr-x  32 bheng  staff    1088 Mar 14 10:00 vendor


Rerun this :


composer require league/flysystem-sftp


Got this :

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^1.0 for league/flysystem-sftp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  /Applications/MAMP/htdocs/code/web-app/vendor/league/flysystem-sftp does not exist and could not be created.





On Mar 14, 2017, at 10:07 AM, Frank de Jonge <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd advice to look at the permissions of the vendor dir and project level permissions.

**Comment by twistor** [comment]
This is a filesystem permissions issue, not an issue with this project. Some Googling will show you how to fix the problem.
