### ISSUE TITLE
Connexion is very slow

### ISSUE THREAD

**Issue by incoming-th** [thephpleague/flysystem-sftp#43]
Hi,

Tested this connector and it is working fine but very slow to do the transfert. When using WinSCP no problem but with this connector it is very slow to get the files / folders.

Any option to add somewhere that I am missing?

**Comment by twistor** [comment]
You'd probably want to ask https://github.com/phpseclib/phpseclib, since this is a thin wrapper over that library.

Off the top of my head, make sure that the OpenSSL extension for PHP installed.

**Comment by incoming-th** [comment]
Will try using SSH key instead of password maybe this will help speed up the transfert based on this https://github.com/phpseclib/phpseclib/issues/1098
