### ISSUE TITLE
DSA and Putty Keys support

### ISSUE THREAD

**Issue by pedrofornaza** [thephpleague/flysystem-sftp#45]
Flysystem-sftp depends on phpseclib, which already have a DSA implementation. There is any limitation preventing to update the phpseclib and using DSA?

**Comment by frankdejonge** [comment]
@pedrofornaza you can pass an instance of `phpseclib\Net\SFTP` as the `NetSftpConnection` configuration parameter, in that case we'll use that. We don't plan to support every flavour of connection management available. This injection is created to support your case specifically.

**Comment by pedrofornaza** [comment]
I will test this approach later.

My only problem is that RSA is hardcoded. Making it configurable would solve it.

Thanks for your time.
