### ISSUE TITLE
Default Laravel Service Provider?

### ISSUE THREAD

**Issue by ragingdave** [thephpleague/flysystem-sftp#46]
I was going to use this plugin and then realized I would have to create a service provider in order to integrate with Laravel.

Questions:
1. Would it be better to create a seperate flysystem-laravel repo to house all the custom serviceproviders? Or maybe a flysystem-sftp-laravel repo to hold this particular one (similiar to glide-laravel)
2. Is there any suggested/recommended file/repo structure to use to add this?

**Comment by frankdejonge** [comment]
Hi, you could make a PR for laravel to add this provider by default, but otherwise a `flysystem-sftp-laravel` repository woudl do the trick. If you decide to create one please let us know so we can link to it in the docs.

**Comment by ragingdave** [comment]
I'll make a PR adding the ServiceProvider here since it's already a plugin type repo.Now that I think about it, doesn't make sense to have to include the main flysystem package, then this one, and then a laravel specific one, which would really only include a single file.

**Comment by frankdejonge** [comment]
@ragingdave A PR for a Laravel service provider will not be accepted here. Please create your own package, or send a PR to Laravel. This project is not tied to Laravel and putting a service-provider here effectively does that.

**Comment by frankdejonge** [comment]
To elaborate more on why this is:

We advocate on separate framework bindings because it allow packages to be updates more freely. Laravel already depends on Flysystem, when Flysystem also depends on Laravel then we're in a upgrade deadlock. It also complicates package maintenance and gives this package too many responsibilities.

**Comment by ragingdave** [comment]
Understood; Misread your original response. I'll make the appropriate pull request and close this. Thanks!

**Comment by frankdejonge** [comment]
@ragingdave 👍 rage on my friend

**Comment by ragingdave** [comment]
@frankdejonge I know I closed this, but I forgot to mention that I did end up creating a repo, 
https://github.com/ragingdave/flysystem-sftp-laravel.

There were a couple other repos, but the naming of the repos or structure, seemed odd or not descriptive enough...plus none had L5.5 auto-discovery yet ;)

**Comment by frankdejonge** [comment]
There's a framework integration section in the main repo readme. Perhaps also send a PR for the Laravel docs?

**Comment by ragingdave** [comment]
I'll get those created and requested.

**Comment by frankdejonge** [comment]
🥇

**Comment by ragingdave** [comment]
Added in PR [#849](https://github.com/thephpleague/flysystem/pull/849)
