### ISSUE TITLE
Property username not set - dependencies with Laravel 4.2

### ISSUE THREAD

**Issue by ncatanchin** [thephpleague/flysystem-sftp#47]
I am working on an older Laravel 4.2 application and want to make use of the SFTP adapter.

```
composer require league/flysystem-sftp
composer require league/flysystem
```

After requiring the two packages, I had the following added to `composer.json`:

```
		"league/flysystem": "^1.1@dev",
		"league/flysystem-sftp": "^1.0@dev"
```

The login method in `SftpAdapter.php` does not use the property "getters", instead it:

```php
 if (! $this->connection->login($this->username, $this->password)) {
```

I've noticed this is fixed in 1.0.12, my `composer.lock` shows I have 1.0.6 installed. I updated composer.json to attempt installation of 1.0.12: `	"league/flysystem-sftp": "^1.0.12@dev"`, but it failed, seemingly due to the requirement for phpseclib 2.

What's the best approach to getting this fix into my current version? Thanks a lot

**Comment by frankdejonge** [comment]
@ncatanchin have you tried also updating to phpseclib 2?
