### ISSUE TITLE
path missing in return value of read and readStream

### ISSUE THREAD

**Issue by weph** [thephpleague/flysystem-sftp#48]
Hello,

flysystem's documentation does not clearly state which values must be included but I've seen that other adapters are returning the path. The SftpAdapter does include it in the result of the write and writeStream methods but it's missing in read and readStream.

**Comment by weph** [comment]
Thanks @frankdejonge 

in which version will this change be in?

**Comment by frankdejonge** [comment]
@weph I've just tagged 1.0.15 so it's now released.
