### ISSUE TITLE
Trouble setting directory permission

### ISSUE THREAD

**Issue by mk-conn** [thephpleague/flysystem-sftp#53]
this is my config:

```
'ssh-machine' => [
            'driver'        => 'sftp',
            'host'          => env('CMS_SSH_HOST'),
            'root'          => env('CMS_SSH_STORAGE_PATH'),
            'port'          => 22,
            'username'      => env('CMS_SSH_USER'),
            'password'      => env('CMS_SSH_PASSWORD', null),
            'privateKey'    => env('CMS_SSH_KEYFILE'),
            'keytext'       => '',
            'keyphrase'     => '',
            'directoryPerm' => 0760,
            'permPublic'    => 0660,
            'visibility'    => 'public',
            //            'agent'      => '',
            'timeout'       => 30
        ]
```

I would expect `drwxrwx---` after a folder is created, but instead I get `drwxr-----` . Is there something I misunderstood or did I do something wrong? 

This is what I do with Laravel
```
// in a provider

   Storage::extend('sftp', function ($app, $config) {
            return new Filesystem(new SftpAdapter($config));
        });

// in 
Storage::disk('ssh-machine')
                                   ->put($attachmentFileName, $rawFile, config('filesystems.disks.ssh-machine'));

//$attachmentFileName is something like /var/www/uploads/attachments/blabla.blub.bla.ext 
```

**Comment by frankdejonge** [comment]
@mk-conn just to be 100% sure, 0760 should result in `drwxrw----`, right? But for the issue itself, we only forward this value 0760 to the sftp connection provided by `phpseclib`. As you can see here (https://github.com/thephpleague/flysystem-sftp/blob/master/src/SftpAdapter.php#L539) we don't process it or anything. Could be something with the FTP server or your user permissions there too. FTP servers are weird and don't all act the same way either. You could rule out any Flysystem related problems by getting the Sftp connection object from the adapter and calling the mkdir function on it yourself. I doubt that'll change things but it could rule something out for you. That way you can open an issue with phpseclib instead.

**Comment by mk-conn** [comment]
@frankdejonge Okay, I'll check that, thx for the hints!

**Comment by frankdejonge** [comment]
👍  you're welcome!
