### ISSUE TITLE
List files under directory is reading/streaming all files

### ISSUE THREAD

**Issue by incoming-th** [thephpleague/flysystem-sftp#54]
Hi,

When I am trying to get a list of files in a directory, I found that all files are read (streamed) in order to get the mimes types maybe, which make connection to be very slow or timeout (this is noticeable when you have files more than 10Mb).

Here is the trace we got when the adaptor is supposed to give back the list of files under a directory, you can see it is reading a 24Mb files.

![33948154-c8654812-e058-11e7-8b35-76cdc1f0f0fe](https://user-images.githubusercontent.com/26375917/33974564-bf3f5120-e0bb-11e7-8415-b3c10591cf00.png)

Any idea? Thanks.

**Comment by frankdejonge** [comment]
@MickaelTH that's not something that's under our controle, we ask for a listing from phpseclib using the `rawlist` method on their connection object. My guess however is that this has to do with how the server itself is configured. We don't explicitly ask for mimetypes in this call.

**Comment by incoming-th** [comment]
@frankdejonge Indeed this is issue with another Driver, thank you for time you tried to check on this issue.

For cross reference, this is the workaround I've found:

https://github.com/barryvdh/elfinder-flysystem-driver/issues/66
