### ISSUE TITLE
Use ssh2.sftp? Memory issues with phpseclib

### ISSUE THREAD

**Issue by LiaraAlis** [thephpleague/flysystem-sftp#60]
Why does the library use the `phpseclib` instead of php built-in functions of ssh2.sftp (http://php.net/manual/de/function.ssh2-sftp.php)?

At the moment, reading a stream via the sftp adapter is consuming a lot of memory. Perhaps, it's better with the php built-in functions (not tried yet)?

**Comment by frankdejonge** [comment]
@LiaraAlis that's because the responses from those calls are very unreliable in terms of format and contents, far worse than the internal FTP calls. If you have performance problems and need to use ssh2.sftp than I suggest writing an adapter for it specifically for your case.

**Comment by LiaraAlis** [comment]
@frankdejonge Wow, very fast – thanks for your response.
If will think about this.

At this moment I can use ftp instead of sftp. I just wondered about the memory problems if I'm using the sftp adapter. So I looked into the code and found that it is completely different.
With the sftp adapter I ran out of memory when I'm trying to download very big files.

Is there no way to fix this problems with the `phpseclib`?

**Comment by frankdejonge** [comment]
@LiaraAlis does your code use the `readStream` method?

**Comment by LiaraAlis** [comment]
@frankdejonge Yes. And with the ftp adapter, all is working fine.

Below is my code.
It is possible to change the adapter via the settings of the album.
```php
    public function downloadAction()
    {
        Shopware()->Plugins()->Controller()->ViewRenderer()->setNoRender();
        $this->Front()->Plugins()->Json()->setRenderer(false);

        $fileId = $this->request->getParam('file');
        $file = $this->getModelManager()->find(File::class, $fileId);

        $conditions = $this->downloadsService->getConditionsForAlbum($file->getAlbumId());
        if (!$this->downloadsService->checkAlbumConditions($conditions)) {
            $this->forward('forbidden');
            return;
        }

        $filesystem = $this->get('bpa_download_center.service.downloads_service')->getFilesystemForAlbum($file->getAlbum());
        $fileData = $filesystem->getMetadata($file->getPath());

        @set_time_limit(0);
        $response = $this->Response();
        $response->setHeader('Content-Type', $filesystem->getMimetype($file->getPath()));
        $response->setHeader('Content-Disposition', 'attachment; filename=' . $file->getName());
        $response->setHeader('Content-Length', $fileData['size']);

        $response->setHeader('Cache-Control', 'public');
        $response->setHeader('Content-Description', 'File Transfer');
        $response->setHeader('Content-Transfer-Encoding', 'binary');

        if (ob_get_level()) ob_end_clean();

        // send headers to client
        $response->sendHeaders();

        $stream = $filesystem->readStream($file->getPath());

        fpassthru($stream);
        exit;
    }
```

**Comment by frankdejonge** [comment]
Then it's phpseclib issue unfortunately. We pass the resource through, the way it's created is out of our control.
