### ISSUE TITLE
Sporadic file not found errors

### ISSUE THREAD

**Issue by alexciarlillo** [thephpleague/flysystem-sftp#67]
I want to preface by saying I am not sure this is an issue with this adapter, but I am wondering how I can further diagnose this to be sure of that...

I am occasionally running into multiple "File not found at path" issues. At first I thought it was legitimate and the hook that was running a download job was firing before the file was finished writing or something. However, after closer inspection and checking the timestamps of the files versus the timestamps of my error logs, I am seeing the files are actually there. I can later repeat the job (manually in a tinker session) and it downloads fine. The main thing I have noticed is that this problem seems to be grouped with a series of jobs for a while (maybe 6-7 jobs error out), then runs fine again for a while. The crux of what I am doing is trying to download cloud meeting recordings for local processing.

Here is a typical error, the rest of the stack trace is all callback and queue stuff:

```
[2018-10-02 22:21:42] production.ERROR: File not found at path: opt/zoom/cmr-storage/replay/2018/10/02/XXXXX/YYYYY/GMT20181002-221928_Untitled---10-02-2018-05-18-pm_1280x720.mp4 {"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: opt/zoom/cmr-storage/replay/2018/10/02/XXXXX/YYYYY/GMT20181002-221928_Untitled---10-02-2018-05-18-pm_1280x720.mp4 at /home/forge/myapp.com/releases/20180928151417/vendor/league/flysystem/src/Filesystem.php:388)
[stacktrace]
#0 /home/forge/myapp.com/releases/20180928151417/vendor/league/flysystem/src/Filesystem.php(194): League\\Flysystem\\Filesystem->assertPresent('opt/zoom/cmr-st...')
#1 /home/forge/myapp.com/releases/20180928151417/app/Jobs/ZoomProcessing/DownloadMeetingRecordings.php(42): League\\Flysystem\\Filesystem->readStream('opt/zoom/cmr-st...')
#2 /home/forge/myapp.com/releases/20180928151417/vendor/laravel/framework/src/Illuminate/Support/Collection.php(397): App\\Jobs\\ZoomProcessing\\DownloadMeetingRecordings->App\\Jobs\\ZoomProcessing\\{closure}('/opt/zoom/cmr-s...', 0)
#3 /home/forge/myapp.com/releases/20180928151417/app/Jobs/ZoomProcessing/DownloadMeetingRecordings.php(47): Illuminate\\Support\\Collection->each(Object(Closure))
#4 [internal function]: App\\Jobs\\ZoomProcessing\\DownloadMeetingRecordings->handle(Object(App\\Services\\Meeting\\ZoomRecordingProcessingService))
```

Here is what I am seeing on the SFTP server:
```
[root@redacted]# pwd   
/opt/zoom/cmr-storage/replay/2018/10/02/XXXXX/YYYYY
[root@redacted]# ls -al --time-style=full-iso
total 3888
drwxr-xr-x 2 root root    4096 2018-10-02 22:21:34.000000000 +0000 .
drwxr-xr-x 3 root root    4096 2018-10-02 22:21:34.000000000 +0000 ..
-rw-r--r-- 1 root root      70 2018-10-02 22:21:34.000000000 +0000 GMT20181002-221928_Untitled---10-02-2018-05-18-pm.vtt
-rw-r--r-- 1 root root 3964667 2018-10-02 22:21:34.000000000 +0000 GMT20181002-221928_Untitled---10-02-2018-05-18-pm_1280x720.mp4
```

The files timestamp is set roughly 8 seconds prior to attempting the download. All the paths appear correct.

And here is the job:

```
public function handle(ZoomRecordingProcessingService $processingSvc)
    {
        $this->filePaths->each(function ($filePath) use ($processingSvc) {
            // open a stream to the file on the recording server
            $fileStream = $processingSvc->remoteRecordings()->getDriver()->readStream($filePath);

            // copy the file to local storage under 'meeting-id/filename'
            $filename = basename($filePath);
            $processingSvc->localRecordings()->put("{$this->meeting->id}/{$filename}", $fileStream);
        });
        \Log::info('Downloaded ' . $this->filePaths->count() . ' recordings for meeting: ' . $this->meeting->id);
    }
```
`remoteRecordings()` just returns the storage disk being handled by the SFTP adapter. And `localRecordings()` is just a local disk.

I feel like this is a pretty straightforward scenario, and it works great 90% of the time. One odd thing I noticed was that Filesystem appears to be stripping the lead '/', at least from what I seeing in the logs, but I am clearly passing it as part of the $filePath. I also even tried a manual test without the '/' and works anyway... I also have 3 retries set for this job (2 seconds apart), when one fails they all fail.

Could the connection be getting stale or something? Any ideas of how I can further debug this?

**Comment by alexciarlillo** [comment]
After further digging looks like this may be caused by the underlying FTP adapter: https://github.com/thephpleague/flysystem/issues/775

**Comment by frankdejonge** [comment]
@alexciarlillo what you describe sounds more like a race condition of some sort. The paths within Flysystem are based on a root, so the leading slash is indeed removed. When your root is `/` this translates into an absolute path, when set to something else this ensures all calls are contained within that root. So that's by design.

**Comment by alexciarlillo** [comment]
Thanks for clarifying the path thing, makes perfect sense and I totally forgot the disk was configured that way. I am going to close this. I can add some additional exception handling and maybe a slight delay in my code to try and reduce any timing related problems, and I will keep an eye on the issue I linked in case it is related/relevant.

Thanks again!

**Comment by frankdejonge** [comment]
👍
