### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by matiux** [thephpleague/flysystem-sftp#7]
I have a problem to upload in sftp...
I use sylex with wyrihaximus/sli-fly service provider, league/flysystem-ziparchive and obviously league/flysystem-sftp.

I have created a zip file and now I need to upload it on sftp server.
This is my config:

```
$app->register(new WyriHaximus\SliFly\FlysystemServiceProvider(), [

    'flysystem.filesystems' => [
        'zip' => [

            'adapter'   => 'League\Flysystem\ZipArchive\ZipArchiveAdapter',
            'args'      => [

                $app['root_dir'].'/web/file.zip',
            ],
        ],
        'sftp' => [

            'adapter'   => 'League\Flysystem\Sftp\SftpAdapter',

            'args'      => [

                [
                    'host'          => '192.241.178.210',
                    'port'          => 22,
                    'username'      => 'my_user,
                    'password'      => 'my_password',
                    'root'          => '/home/user/Documents/html/stream',
                    'timeout'       => 30,
                ]
            ]
        ]
    ],
]);
```

I create the zip file:

```
$this->filesystems['zip']->put('file.xml', $xml);
```

but when I try to upload it

```
$this->filesystems['sftp']->put('file.zip', '/var/www/Projects/Acme/web/file.zip');
```

On the server, file.zip was created, but it's a invalid file that I don't can open

**Comment by frankdejonge** [comment]
@wyrihaximus would you happen to know what's going on here? I haven't used your Silex package :)

**Comment by WyriHaximus** [comment]
@frankdejonge while `wyrihaximus/sli-fly` is just an ultra thin wrapper that returns the flysystem filesystem object but lets see if we can figure out what is going wrong :+1: .

@matiux Does the size match the size locally? Can you open the local version? Honestly I haven't used the zip adapter my self but does it needs to be closed somehow @frankdejonge? Does a regular file upload work for you?

**Comment by frankdejonge** [comment]
@matiux I might be mistaking, but I think you've misinterpreted what `put` does. That method needs the contents of the file, not the file location. @WyriHaximus makes sense to you?

**Comment by WyriHaximus** [comment]
@frankdejonge makes perfect sense to me: `$this->filesystems['sftp']->put('file.zip', file_get_contents($app['root_dir'].'/web/file.zip'));` should do the trick I suppose :smile:
