### ISSUE TITLE
Connection closed prematurely

### ISSUE THREAD

**Issue by hasiashiana** [thephpleague/flysystem-sftp#76]
Hi,

I have an application which gets the data from CSV as a collection and send to a SFTP path. I am using this flysystem-sftp and everything was working fine and suddenly started to get 'Connection closed prematurely' error for my job which send the file to SFTP. Nothing is changed on my code .

SFTP server user a private key for authentication. Can some one help me figure out the problem

**Comment by kimdungg** [comment]
Hi @hasiashiana, could you share with me how you handled it? I ran into the same issue and didn't find any related solution to this.
