### ISSUE TITLE
privateKey configuration : wrong case

### ISSUE THREAD

**Issue by tehla** [thephpleague/flysystem-sftp#78]
Hello

Your `protected $configurable` property is wrong for your `SftpAdater`. You are declaring a 'privateKey' value (with uppercase K), but you are using a `protected $privatekey` property (with lowercase k)

This make the private key parameter unusable, when you instanciate your adapter.
I tried with a lowercase K in the `protected $configurable` declarations and in the configuration key when instanciating, and it works better.

You should use the same lowercase/uppercase naming in declaration/property/documentation.
Could you fix it please ?
Best Regards

**Comment by frankdejonge** [comment]
Fixed in your PR.

**Comment by frankdejonge** [comment]
Release `1.0.19` is just pushed.

**Comment by tehla** [comment]
Thx, that works fine now :-)
