### ISSUE TITLE
Downloading content breaks encoding

### ISSUE THREAD

**Issue by Nizari** [thephpleague/flysystem-sftp#83]
I've uploaded an file on an sftp server which I can get the content from like:

`$content = Storage::disk('sftp')->get($remoteFile);`

However instead of the following content:
_Apprendre à lire très vite, c'est possible, mais ça n'a aucun sens_
I get:
_**b"**Apprendre ê lire tr**Å**s vite, c'est possible, mais ìa n'a aucun sens"_

Is there a way to enforce utf8 encoding?

**Comment by frankdejonge** [comment]
Flysystem does not concern itself with the encoding. You should ask this in the laravel repo, probably you need some settings on the response.
