### ISSUE TITLE
Typo error on SftpAdapter getMetadata method

### ISSUE THREAD

**Issue by victorteran93** [thephpleague/flysystem-sftp#85]
Hi,

A colleague and I believe found a error in this method:

```
public function getMetadata($path)
    {
        $connection = $this->getConnection();
        $info = $connection->stat($path);
        if ($info === false) {
            return false;
        }
        $result = Util::map($info, $this->statMap);
        $result['type'] = $info['type'] === NET_SFTP_TYPE_DIRECTORY ? 'dir' : 'file';
        $result['visibility'] = $info['permissions'] & $this->permPublic ? 'public' : 'private';
        return $result;
    }
```

We think the line: 

`$result['visibility'] = $info['permissions'] & $this->permPublic ? 'public' : 'private';`

should be:

`$result['visibility'] = $info['permissions'] **&&** $this->permPublic ? 'public' : 'private';`

**Comment by frankdejonge** [comment]
Hi @victorteran93 the `&` operator is one of the bitwise operators. It basically does a binary comparison to see if there's a inclusive match. You can read more about it here: https://www.php.net/manual/en/language.operators.bitwise.php

**Comment by victorteran93** [comment]
Hi Frank,

We are getting this traceback: 
```
ErrorException: A non-numeric value encountered/home/vagrant/code/github/integration/vendor/league/flysystem-sftp/src/SftpAdapter.php:514
/home/vagrant/code/github/integration/vendor/league/flysystem-sftp/src/SftpAdapter.php:497
/home/vagrant/code/github/integration/vendor/league/flysystem/src/Filesystem.php:57
/home/vagrant/code/github/integration/vendor/league/flysystem/src/Filesystem.php:388
/home/vagrant/code/github/integration/vendor/league/flysystem/src/Filesystem.php:179
/home/vagrant/code/github/integration/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:107
/home/vagrant/code/github/integration/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php:368
/home/vagrant/code/github/integration/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
```
And the values for $info['permissions'] ,  $this->permPublic are  [
  0 => "public"
  1 => 484
] we thought the problem is comparision string with number, we are using php7.1.

**Comment by victorteran93** [comment]
Hi, we check and you are right, the problem was from us because is a unit test and the mock was wrong, tbanks.
