### ISSUE TITLE
Can't see files

### ISSUE THREAD

**Issue by CraigHarley** [thephpleague/flysystem-sftp#88]
This might be something I'm doing wrong, but here goes:

I've got a user on a server I can ssh into - everything works, can see all the files I need to, no problem.

I can FileZilla (using SFTP, all the same creds, password auth is turned off), again everything works, can see all the files I need to, no problem.

Connect with this package, same creds, connection succeeds and I can see **only** the root folder (/).
Everything is empty and I can't see either the user directory(~) or the mounted disk contents ('/mnt/').

I've tried re-chowning and re-chmodding but that doesn't help, I don't think it's permissions because I can see the files on other SFTP clients and using SSH as the same user.

**Comment by frankdejonge** [comment]
Hi, can you check what the raw responses the adapter gets from phpseclib? This might give some more information to see what's going on.

**Comment by CraigHarley** [comment]
@frankdejonge thanks for the response!

Gladly, how do I do this?

**Comment by frankdejonge** [comment]
You can change the adapter code and var_dump the response, or use step through debugging.

**Comment by CraigHarley** [comment]
Looks like it's just `false` coming back from `$connection->rawlist`

**Comment by frankdejonge** [comment]
Then it appears to be an issue with either your configuration or it's a bug within phpseclib.

**Comment by CraigHarley** [comment]
Odd that I can see some stuff though, if there was an issue with the config I'd expect it to bork out early.

**Comment by frankdejonge** [comment]
Yeah, you'd say so. But then again, FTP (in any shape or form).

**Comment by CraigHarley** [comment]
Here's the raw at the root (just the folder I'm after, I can send the rest if it helps).
```php
array:28 [
  // more above ...
  "mnt" => array:9 [
    "size" => 4096
    "uid" => 0
    "gid" => 0
    "permissions" => 16877
    "mode" => 16877
    "type" => 2
    "atime" => 1568711852
    "mtime" => 1568037270
    "filename" => "mnt"
  ],
  // more below ...
]
```

**Comment by CraigHarley** [comment]
I have the same issue on another server, using https://github.com/thephpleague/flysystem-sftp, so I don't think this is an issue with this package. So I'll close this issue.

Thanks for the help anyway @frankdejonge.
