### ISSUE TITLE
readStream returns an array instead of a stream

### ISSUE THREAD

**Issue by pies** [thephpleague/flysystem-sftp#9]
When I do `$sftpAdapter->readStream($path)` it returns an array that contains the stream under the `stream` key. Is that necessary? Shouldn't it return an actual stream?

**Comment by frankdejonge** [comment]
@pies Hi, I think you're using the adapter stand-alone, using an adapter should never be done directly, it should be wrapped in a `League\Flysystem\Filesystem` class.

``` php
$adapter = new FtpsAdapter();
$filesysystem = new League\Flysystem\FIlesystem($adapter);

$stream = $filesystsem->readStream($path);
```
